message-push:
  git_url: https://github.com/opensourceways/message-push.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/ea5489fc52984d36a1b33fc6378ddb85?from=out-project&v=1
  endpoint_id: a00c8423f08b4f2fb68c72bd739d4f48
  owner: shishupei, zhaokunhang,hourunze
  mail: shishupei@huawei.com, zhaokunhang@huawei.com,hourunze@h-partners.com

message-transfer:
  git_url: https://github.com/opensourceways/message-transfer.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/9aa09cdf0a864a9f8cb01f2254bbde17?from=in-project&v=1
  endpoint_id: 3d8e02477789490fb10b885e927c027d
  owner: shishupei, zhaokunhang,hourunze
  mail: shishupei@huawei.com, zhaokunhang@huawei.com,hourunze@h-partners.com

message-collect:
  git_url: https://github.com/opensourceways/message-collect.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/5719a88575cf416dbf5fb8186a4997ce?from=in-project&v=1
  endpoint_id: 0ac98ded10804596b13d2341ede6e5b6
  owner: shishupei, zhaokunhang,hourunze
  mail: shishupei@huawei.com, zhaokunhang@huawei.com,hourunze@h-partners.com

BigFiles:
  git_url: https://github.com/opensourceways/BigFiles.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/58d2a62564c14ce1815dcce4d1064020?from=in-project&v=1
  endpoint_id: 213f55413c51481da30769de540a5577
  owner: jufangqun, zhouyi, zhaokunhang
  mail: jufangqun@huawei.com, zhouyi198@h-partners.com, zhaokunhang@huawei.com

certification-server:
  git_url: https://github.com/opensourceways/certification-server.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/128c1a12cee14cd3ae4059676f9c3c61?from=out-project&v=1
  endpoint_id: 8c4ad6369c294b33865f286154e64605
  owner: zhaoyan, liyanghang, zhaokunhang
  mail: zhaoyan150@huawei.com, liyanghang@huawei.com, zhaokunhang@huawei.com

message-manager:
  git_url: https://github.com/opensourceways/message-manager.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/e5989fec9a70450e986fdce82f0e09dc?from=out-project&v=1
  endpoint_id: 34a107fde9ee4c828f70cd8f23e4e115
  owner: hourunze, shishupei, zhaokunhang
  mail: hourunze@h-partners.com, shishupei@huawei.com, zhaokunhang@huawei.com

EasySoftwareService:
  git_url: https://github.com/opensourceways/EasySoftwareService.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/99c7d59e96c74d5c963cbf39a9049518?from=in-project&v=1
  endpoint_id: 582a9b18ea9e4d8993b4461761d3f1d3
  owner: xiechengzhi, zhaiwenjie, zhaokunhang
  mail: xiechengzhi3@h-partners.com, zhaiwenjie1@huawei.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com

EasySoftwareInput:
  git_url: https://github.com/opensourceways/EasySoftwareInput.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/704fc4f23f8a43efaa7a470bbb0b99ec?from=in-project&v=1
  endpoint_id: ba94ad848e4f4fe399650626298f0f74
  owner: gouzhonglin, zhaiwenjie, zhaokunhang
  mail: gouzhonglin@huawei.com, zhaiwenjie1@huawei.com, zhaokunhang@huawei.com

easysoftware-autoupgrade:
  git_url: https://github.com/opensourceways/easysoftware-autoupgrade.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/dfffe2767c914e96aa7e7ae294ba567c?from=in-project&v=1
  endpoint_id: 94d7a318bf27475291fde12d4e2fc4e2
  owner: lifan, zhaiwenjie, zhaokunhang
  mail: lifan140@h-partners.com, zhaiwenjie1@huawei.com, zhaokunhang@huawei.com

go-gitcode:
  git_url: https://github.com/opensourceways/go-gitcode.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/4d0001dbe76242f99bd0cf1e9a61917b?from=in-project&v=1
  endpoint_id: 03237f39828f4e79a0d03e0f22dd9d4c
  owner: fengchao, zhaokunhang
  mail: fengchao73@h-partners.com, zhaokunhang@huawei.com

om-webserver:
  git_url: https://github.com/opensourceways/om-webserver.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/096058e3d0e941ec8eba54e20a928f3f?from=in-project&v=1
  endpoint_id: 52be143a360543c6919f5eff2d89ba1e
  owener: taofeihu
  mail: taofeihu1@huawei.com, zhaokunhang@huawei.com
  branch: stable
  
oneid-server:
  git_url: https://github.com/opensourceways/oneid-server.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/ad194e75781f4cde9fe483e15e4d8c69?from=in-project&v=1
  endpoint_id: 70c928f5254f42f5af7980c4dd274036
  owener: taofeihu
  mail: taofeihu1@huawei.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com

datastat-server:
  git_url: https://github.com/opensourceways/datastat-server.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/66fb93d75f8d41f0a1082bbf4770f5a9?from=in-project&v=1
  endpoint_id: 383974d1f5764ae98ddc46fc3245265e
  owener: wucaiping
  mail: wucaiping1@huawei.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com

EasySearch:
  git_url: https://github.com/opensourceways/EasySearch.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/5288ca277b674b3393450c0bd0f0d6d5?from=out-project&v=1
  endpoint_id: 7e0dd4f853a44979a8d51ea779b1a1ac
  owener: lifan
  mail: lifan140@h-partners.com, zhaokunhang@huawei.com,jun.zhongjun@huawei.com
  branch: refactor

EasySearch-Import:
  git_url: https://github.com/opensourceways/EasySearch-Import.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/0dfc2b00b34c48868ac855f62a1586aa?from=in-project&v=1
  endpoint_id: 7fbfbfdb3ef44a82b1a4dcdfcd5a2506
  owener: lifan
  mail: lifan140@h-partners.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com
  
om-kafka:
  git_url: https://github.com/opensourceways/om-kafka.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/434e2323aa3e44449b7fe5cc2a24c2b6?from=out-project&v=1
  endpoint_id: 833845f535f344a381b9466c16ee3840
  owener: taofeihu
  mail: taofeihu1@huawei.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com

xihe-server:
  git_url: https://github.com/opensourceways/xihe-server
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/5c049736c2cd46ba9a4c8bbcbc5e0fca?from=in-project&v=1
  endpoint_id: 70d9403856274939a703351894b1f1d3
  owener: zhongyuanke
  mail: zhongyuanke@huawei.com, zhouyi198@h-partners.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com, shishupei@huawei.com

om-collections:
  git_url: https://github.com/opensourceways/om-collections.git
  pipeline_url: https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/history/a3b7a0a70d67475ab4cffdd760d24e05?from=in-project&v=1
  endpoint_id: c5c466e5104f45c4930ba258ba8e4c18
  owener: wucaiping
  mail: wucaiping1@huawei.com, zhaokunhang@huawei.com, jun.zhongjun@huawei.com

